### Get Events
GET  http://localhost:8181/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc0NDgzMjQsImlkIjoxLCJ1c2VybmFtZSI6Imt1c3VtYWJyaWFudG9ubzlAZ21haWwuY29tIn0.omJnu09eRs3sg4EXfZManpPlvitY6rIgvfShkEi06F8

### Create Event
POST http://localhost:8181/auth/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc0NDgzMjQsImlkIjoxLCJ1c2VybmFtZSI6Imt1c3VtYWJyaWFudG9ubzlAZ21haWwuY29tIn0.omJnu09eRs3sg4EXfZManpPlvitY6rIgvfShkEi06F8

{
  "title": "Test Event 2",
  "description": "A Test Event 2",
  "location": "A Test Location 2",
  "datetime": "2025-01-01T15:30:00.000Z"
}

### Get Event
GET http://localhost:8181/events/1

### Update Event
PUT http://localhost:8181/events/1
content-type: application/json

{
  "title": "Test Event Updated Z2",
  "description": "A Test Event Updated Z2",
  "location": "A Test Location Updated Z2",
  "datetime": "2025-01-01T15:30:00.000Z"
}

### Delete Event
DELETE http://localhost:8181/events/1