### Register Events
POST  http://localhost:8181/events/5/register
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc0ODExNDYsImlkIjoxLCJ1c2VybmFtZSI6InVzZXIxIn0.9csmEl-WpNbzbEGFKqo1sq_ROUr8w3kRgybfJGZnFG0
